[package]
name = "naqshsmith-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
num-traits = "0.2"
itertools = "*"
rand = "*"
embedded-graphics = "*"
tinytga = "*"